# Generated by Django 4.0.4 on 2022-05-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_question_section"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="updated_by",
        ),
        migrations.CreateModel(
            name="QuestionEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="upadated_at"),
                ),
                (
                    "exam_stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_states",
                        to="enrollments.examthroughenrollment",
                        verbose_name="exam_stat",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="exams.question",
                        verbose_name="question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_choices",
                        to="exams.option",
                        verbose_name="selected_option",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuestionEnrollment",
                "verbose_name_plural": "QuestionEnrollments",
                "ordering": ["-updated_at"],
            },
        ),
    ]
