# Generated by Django 4.0.4 on 2022-05-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_question_section"),
        ("enrollments", "0002_remove_enrollment_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="exam",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="exams.exam",
                verbose_name="exam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                default="inactive",
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
