# Generated by Django 4.0.4 on 2022-05-26 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enrollments", "0003_session_exam_alter_session_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="student",
            ),
        ),
    ]
