# Generated by Django 4.0.4 on 2022-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0004_alter_enrollment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examthroughenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("attempted", "attempted"),
                    ("started", "started"),
                    ("finished", "finished"),
                    ("failed", "failed"),
                    ("passed", "passed"),
                    ("completed", "completed"),
                ],
                default="created",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("ended", "ended"),
                ],
                default="inactive",
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
