# Generated by Django 4.0.4 on 2022-05-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_exam_status"),
        ("enrollments", "0005_alter_examthroughenrollment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionenrollment",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_choices",
                to="exams.option",
                verbose_name="selected_option",
            ),
        ),
    ]
