# Generated by Django 3.2.13 on 2022-06-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_exam_status"),
        ("enrollments", "0006_alter_questionenrollment_selected_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionenrollment",
            name="selected_option",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_choices",
                to="exams.option",
                verbose_name="selected_option",
            ),
            preserve_default=False,
        ),
    ]
