# Generated by Django 3.2.13 on 2022-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0007_alter_questionenrollment_selected_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="end_task",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="end_task"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="start_task",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="start_task"
            ),
        ),
    ]
