# Generated by Django 3.2.13 on 2022-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0011_auto_20220605_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("ended", "ended"),
                    ("resultsout", "resultsout"),
                ],
                default="inactive",
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
