# Generated by Django 3.2.13 on 2022-06-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options"),
        ("physicalbook", "0002_auto_20220608_1534"),
        ("enrollments", "0011_auto_20220605_1614"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseThroughEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("initiated", "initiated"),
                            ("on-hold", "on-hold"),
                            ("progress", "progress"),
                            ("declined", "declined"),
                            ("final phase", "final phase"),
                            ("completed", "completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joining_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "selected_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollments.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalBookCourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_provided", models.BooleanField(default=False)),
                (
                    "course_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollments.coursethroughenrollment",
                    ),
                ),
                (
                    "physical_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="physicalbook.physicalbook",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="courses",
            field=models.ManyToManyField(
                related_name="enrollments",
                through="enrollments.CourseThroughEnrollment",
                to="courses.Course",
            ),
        ),
    ]
