# Generated by Django 3.2.13 on 2022-06-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0012_alter_session_status"),
        ("enrollments", "0012_auto_20220609_1648"),
    ]

    operations = []
