# Generated by Django 3.2.13 on 2022-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0012_alter_session_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="session",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
