# Generated by Django 3.2.13 on 2022-06-14 05:06

from django.db import migrations


def publish_all_pervious(apps, schema_editor):
    """Publish all previous session instances."""
    # We can't import the models directly as they may be
    # out of date for this migration. We use the historical version.
    Session = apps.get_model("enrollments", "Session")
    for sess in Session.objects.all():
        sess.is_published = True
        sess.save()


def publish_all_previous_reverse(apps, schema_editor):
    """Unpublish all previous session instances."""
    # We can't import the models directly as they may be
    # out of date for this migration. We use the historical version.
    Session = apps.get_model("enrollments", "Session")
    for sess in Session.objects.all():
        sess.is_published = False
        sess.save()


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0013_auto_20220614_1040"),
    ]

    operations = [
        migrations.RunPython(publish_all_pervious, publish_all_previous_reverse),
    ]
