# Generated by Django 3.2.13 on 2022-06-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0014_auto_20220613_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examthroughenrollment",
            name="selected_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_enrolls",
                to="enrollments.session",
                verbose_name="exam_session",
            ),
        ),
    ]
