# Generated by Django 3.2.13 on 2022-06-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0015_alter_examthroughenrollment_selected_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalbookcourseenrollment",
            name="course_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physical_books",
                to="enrollments.coursethroughenrollment",
            ),
        ),
    ]
