# Generated by Django 3.2.13 on 2022-06-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physicalbook", "0002_auto_20220608_1534"),
        ("enrollments", "0016_alter_physicalbookcourseenrollment_course_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalbookcourseenrollment",
            name="course_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physicalbook_enrolls",
                to="enrollments.coursethroughenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="physicalbookcourseenrollment",
            name="physical_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physicalbook_enrolls",
                to="physicalbook.physicalbook",
            ),
        ),
    ]
