# Generated by Django 3.2.13 on 2022-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0014_auto_20220614_1051"),
        ("enrollments", "0018_auto_20220615_1214"),
    ]

    operations = []
