# Generated by Django 3.2.13 on 2022-06-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0019_merge_0014_auto_20220614_1051_0018_auto_20220615_1214"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursethroughenrollment",
            options={
                "verbose_name": "CourseThroughEnrollment",
                "verbose_name_plural": "CourseThroughEnrollments",
            },
        ),
    ]
