# Generated by Django 3.2.13 on 2022-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0020_alter_coursethroughenrollment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursethroughenrollment",
            name="course_status",
        ),
        migrations.AddField(
            model_name="coursethroughenrollment",
            name="course_enroll_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("initiated", "initiated"),
                    ("on-hold", "on-hold"),
                    ("progress", "progress"),
                    ("canceled", "canceled"),
                    ("final phase", "final phase"),
                    ("completed", "completed"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
