# Generated by Django 3.2.13 on 2022-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0022_alter_coursethroughenrollment_completed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursethroughenrollment",
            name="completed_date",
            field=models.DateTimeField(),
        ),
    ]
