# Generated by Django 3.2.13 on 2022-07-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_coursecategory_options"),
        ("exams", "0019_auto_20220624_1549"),
        ("enrollments", "0023_alter_coursethroughenrollment_completed_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="session",
            name="status",
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "session_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enrollments.session",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("ended", "ended"),
                            ("resultsout", "resultsout"),
                        ],
                        default="inactive",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
            },
            bases=("enrollments.session",),
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "session_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enrollments.session",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("ended", "ended"),
                        ],
                        default="inactive",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                ("link", models.URLField()),
                ("password", models.CharField(max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Session",
                "verbose_name_plural": "Course Sessions",
            },
            bases=("enrollments.session",),
        ),
    ]
