# Generated by Django 3.2.13 on 2022-07-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0023_alter_coursethroughenrollment_completed_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["-id"],
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
    ]
