# Generated by Django 3.2.13 on 2022-07-05 09:52

from django.db import migrations

import common.modelFields


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0024_alter_session_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="end_date",
            field=common.modelFields.ZeroSecondDateTimeField(verbose_name="end_date"),
        ),
    ]
