# Generated by Django 3.2.13 on 2022-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0024_auto_20220701_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursethroughenrollment",
            name="course_enroll_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("initiated", "initiated"),
                    ("on-hold", "on-hold"),
                    ("progress", "progress"),
                    ("canceled", "canceled"),
                    ("completed", "completed"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
