# Generated by Django 3.2.13 on 2022-07-03 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0025_alter_coursethroughenrollment_course_enroll_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursethroughenrollment",
            name="selected_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrolls",
                to="enrollments.coursesession",
            ),
        ),
        migrations.AlterField(
            model_name="examthroughenrollment",
            name="selected_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_enrolls",
                to="enrollments.examsession",
                verbose_name="exam_session",
            ),
        ),
    ]
