# Generated by Django 3.2.13 on 2022-07-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0022_examimage"),
        ("enrollments", "0025_alter_session_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
                "ordering": ["-id"],
            },
        ),
    ]
