# Generated by Django 3.2.13 on 2022-07-28 06:17

from django.db import migrations

from enrollments.models import ExamSession


def transfer_exam_from_session_to_exam_session(apps, schema_editor):
    Session = apps.get_model("enrollments", "Session")
    ExamSession = apps.get_model("enrollments", "ExamSession")
    for session in Session.objects.all():
        exam_session = ExamSession(
            exam=session.exam,
        )
        exam_session.save()


def reverse_exam_from_session_to_exam_session(apps, schema_editor):
    ExamSession = apps.get_model("enrollments", "ExamSession")
    ExamSession.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0026_examsession"),
    ]

    operations = [
        migrations.RunPython(
            transfer_exam_from_session_to_exam_session,
            reverse_exam_from_session_to_exam_session,
        ),
    ]
