# Generated by Django 3.2.13 on 2022-07-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0027_auto_20220728_1202"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="exam",
        ),
    ]
