# Generated by Django 3.2.13 on 2022-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0029_auto_20220728_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="result_is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examsession",
            name="result_publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
