# Generated by Django 3.2.13 on 2022-07-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0030_auto_20220728_1520"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examsession",
            options={
                "ordering": ["-session_ptr__id"],
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
            },
        ),
    ]
