# Generated by Django 3.2.13 on 2022-07-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0032_auto_20220728_1803"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="session",
            name="publish_date",
        ),
    ]
