# Generated by Django 3.2.13 on 2022-08-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0022_examimage"),
        ("enrollments", "0033_auto_20220728_1826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsession",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="exams.exam",
                verbose_name="exam",
            ),
        ),
    ]
