# Generated by Django 3.2.13 on 2022-08-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_merge_20220701_1042"),
        ("enrollments", "0034_alter_examsession_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "session_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enrollments.session",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Session",
                "verbose_name_plural": "Course Sessions",
                "ordering": ["-session_ptr__id"],
            },
            bases=("enrollments.session",),
        ),
    ]
