# Generated by Django 3.2.13 on 2022-08-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0037_alter_coursethroughenrollment_selected_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursethroughenrollment",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_enrolls",
                to="enrollments.enrollment",
            ),
        ),
    ]
