# Generated by Django 3.2.13 on 2022-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0040_examthroughenrollment_negative_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(
                default="NewSession", max_length=255, verbose_name="name"
            ),
        ),
    ]
