# Generated by Django 3.2.13 on 2022-11-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0041_session_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursethroughenrollment",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
