# Generated by Django 3.2.13 on 2022-12-12 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0042_alter_coursethroughenrollment_completed_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursethroughenrollment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examthroughenrollment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
