# Generated by Django 3.2.13 on 2022-12-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0043_alter_examthroughenrollment_options"),
        ("enrollments", "0043_auto_20221212_1834"),
    ]

    operations = []
