# Generated by Django 3.2.13 on 2023-01-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0043_alter_examthroughenrollment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursethroughenrollment",
            name="attended_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coursethroughenrollment",
            name="class_meet_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
