# Generated by Django 3.2.13 on 2022-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "is_displayed",
                    models.BooleanField(default=False, verbose_name="is_displayed"),
                ),
            ],
            options={
                "verbose_name": "BannerAd",
                "verbose_name_plural": "BannerAds",
                "ordering": ["id"],
            },
        ),
    ]
