# Generated by Django 3.2.13 on 2022-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannerad", "0002_auto_20221124_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerad",
            name="img",
            field=models.ImageField(default="exit", upload_to="", verbose_name="img"),
            preserve_default=False,
        ),
    ]
