# Generated by Django 3.2.13 on 2023-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stafftracking", "0003_staffconnectionstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffconnectionstatus",
            name="is_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
