# Generated by Django 3.2.13 on 2023-03-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stafftracking", "0004_staffconnectionstatus_is_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffconnectionstatus",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffconnectionstatus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
