# Generated by Django 3.2.13 on 2022-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models

import physicalbook.models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_instructor_id_remove_course_type_id"),
        ("physicalbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalbook",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="physical_books",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="physicalbook",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=physicalbook.models.PhysicalBook.physical_book_location,
            ),
        ),
    ]
