# Generated by Django 3.2.13 on 2023-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physicalbook", "0002_auto_20220608_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalbook",
            name="sub_topic",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
