# Generated by Django 4.0.4 on 2022-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
