# Generated by Django 3.2.13 on 2022-06-16 04:20

from django.db import migrations


def create_profile_for_all_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, defaults={"user": user})


def delete_profile_for_all_users(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile"),
    ]

    operations = [
        migrations.RunPython(
            create_profile_for_all_users, delete_profile_for_all_users
        ),
    ]
