# Generated by Django 3.2.13 on 2022-08-19 10:23

from django.db import migrations, models

import accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that phone already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[accounts.validators.PhoneNumberValidator()],
                verbose_name="username",
            ),
        ),
    ]
