# Generated by Django 3.2.13 on 2022-08-29 10:45

import datetime

from django.db import migrations, models
from django.utils.timezone import utc

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="qr_code",
            field=models.ImageField(
                default=datetime.datetime(2022, 8, 29, 10, 45, 21, 13087, tzinfo=utc),
                upload_to=accounts.models.Profile.qr_code_image_upload,
            ),
            preserve_default=False,
        ),
    ]
