# Generated by Django 3.2.13 on 2022-08-30 08:44

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_profile_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="qr_code",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts.models.Profile.qr_code_image_upload,
            ),
        ),
    ]
