# Generated by Django 3.2.13 on 2022-08-30 10:02

import os

import segno
from django.conf import settings
from django.core import signing
from django.db import migrations


def create_qrcode_for_all_users(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for obj in Profile.objects.all():
        user_phone = obj.user.username
        secret_generator = signing.Signer(salt=settings.SECRET_KEY)
        encripted_user = secret_generator.sign_object(user_phone)
        qr_img = segno.make(encripted_user, micro=False)
        media_path = f"qr_code/{user_phone}"
        base_path = os.path.join(settings.BASE_DIR, f"media/{media_path}")
        os.makedirs(base_path, exist_ok=True)
        qr_img.save(f"{base_path}/qr.svg", scale=10)
        obj.qr_code = f"{media_path}/qr.svg"
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_qr_code"),
    ]

    operations = [
        migrations.RunPython(
            create_qrcode_for_all_users, reverse_code=migrations.RunPython.noop
        )
    ]
