# Generated by Django 3.2.13 on 2022-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220830_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'GENERAL TEACHER'), (3, 'GENERAL DIRECTOR'), (4, 'STUDENT')], null=True),
        ),
    ]
