# Generated by Django 3.2.13 on 2022-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'TEACHER'), (3, 'DIRECTOR'), (4, 'STUDENT')], null=True),
        ),
    ]
