# Generated by Django 3.2.13 on 2022-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Super Admin"),
                            (2, "Admin"),
                            (3, "Director"),
                            (4, "Teacher"),
                            (5, "Accountant"),
                            (6, "Cashier"),
                            (7, "Counsellor"),
                            (8, "Staff"),
                            (9, "Student"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(to="accounts.Role"),
        ),
    ]
