# Generated by Django 3.2.13 on 2022-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20221122_1509"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
