# Generated by Django 3.2.13 on 2022-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_auto_20221116_1635"),
        ("accounts", "0018_profile_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(blank=True, to="courses.CourseCategory"),
        ),
    ]
