# Generated by Django 3.2.13 on 2023-05-24 05:04

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Group = apps.get_model("auth", "Group")

    CONTENT_CREATOR = 10
    role_choices = ((CONTENT_CREATOR, "Content Creator"),)

    for choices in role_choices:
        Role.objects.get_or_create(id=choices[0])
        Group.objects.get_or_create(name=choices[1])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Super Admin"),
                    (2, "Admin"),
                    (3, "Director"),
                    (4, "Teacher"),
                    (5, "Accountant"),
                    (6, "Cashier"),
                    (7, "Counsellor"),
                    (8, "Staff"),
                    (9, "Student"),
                    (10, "Content Creator"),
                ],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
