# Generated by Django 3.2.13 on 2024-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_accountdeleteion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountdeleteion",
            options={"ordering": ["id"]},
        ),
    ]
