# Generated by Django 3.2.13 on 2022-09-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_alter_course_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_id", models.CharField(max_length=255, verbose_name="host_id")),
                (
                    "host_email",
                    models.EmailField(max_length=254, verbose_name="host_email"),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="topic")),
                ("type", models.IntegerField(verbose_name="type")),
                (
                    "occurence_status",
                    models.CharField(max_length=64, verbose_name="occurence_status"),
                ),
                ("start_time", models.DateTimeField(verbose_name="start_time")),
                ("password", models.CharField(max_length=255, verbose_name="password")),
                ("created_at", models.DateTimeField(verbose_name="createdAt")),
                ("agenda", models.CharField(max_length=255, verbose_name="agenda")),
                ("duration", models.DurationField(verbose_name="duration")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
            },
        ),
    ]
