# Generated by Django 3.2.13 on 2022-09-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_auto_20220912_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="type",
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_type",
            field=models.IntegerField(default=2, verbose_name="meeting_type"),
            preserve_default=False,
        ),
    ]
