# Generated by Django 3.2.13 on 2022-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_auto_20220914_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="meeting_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="variant",
            field=models.CharField(
                choices=[("zoom", "zoom")],
                default="zoom",
                max_length=32,
                verbose_name="variant",
            ),
        ),
    ]
