# Generated by Django 3.2.13 on 2022-09-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0040_examthroughenrollment_negative_score"),
        ("meetings", "0004_auto_20220914_1540"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="course",
        ),
        migrations.AddField(
            model_name="meeting",
            name="course_session",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="enrollments.coursesession",
                verbose_name="course_session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="end_date_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="end_date_time"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="monthly_day",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="monthly_day"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="repeat_interval",
            field=models.PositiveIntegerField(
                default=1, verbose_name="repeat_interval"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="repeat_type",
            field=models.PositiveIntegerField(default=1, verbose_name="repeat_type"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="weekly_days",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="weekly_days"
            ),
        ),
    ]
