# Generated by Django 3.2.13 on 2022-09-25 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_auto_20220919_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="monthly_day",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="monthly_day",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="repeat_type",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="repeat_type",
            ),
        ),
    ]
