# Generated by Django 3.2.13 on 2022-09-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_auto_20220925_1831"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="password",
            field=models.CharField(max_length=10, verbose_name="password"),
        ),
    ]
