# Generated by Django 3.2.13 on 2023-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_alter_meeting_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="meeting_status",
            field=models.CharField(
                choices=[("inactive", "Inactive"), ("active", "Active")],
                default="inactive",
                max_length=64,
                verbose_name="meeting_status",
            ),
        ),
    ]
