# Generated by Django 3.2.13 on 2023-03-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
    ]
