# Generated by Django 4.0.4 on 2022-05-24 09:11

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "num_of_questions",
                    models.IntegerField(default=0, verbose_name="num_of_questions"),
                ),
                (
                    "pos_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=5,
                        verbose_name="pos_marks",
                    ),
                ),
                (
                    "neg_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.4"),
                        max_digits=5,
                        verbose_name="neg_marks",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.examtemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.TextField(verbose_name="detail")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/",
                        verbose_name="img",
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        max_digits=5,
                        verbose_name="marks",
                    ),
                ),
                (
                    "neg_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.4"),
                        max_digits=5,
                        verbose_name="neg_marks",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="feedback"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["exam", "id"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.TextField(verbose_name="detail")),
                ("correct", models.BooleanField(default=False, verbose_name="correct")),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="options/", verbose_name="img"
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="marks",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "ordering": ["question", "id"],
            },
        ),
    ]
