# Generated by Django 4.0.4 on 2022-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("exams", "0002_section_question_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)ss",
                to="courses.coursecategory",
                verbose_name="categories",
            ),
        ),
    ]
