# Generated by Django 4.0.4 on 2022-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_exam_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examtemplate",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="examtemplate",
            name="pass_score",
        ),
        migrations.RemoveField(
            model_name="option",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="question",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="question",
            name="neg_marks",
        ),
        migrations.AddField(
            model_name="examtemplate",
            name="full_marks",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="full_marks"
            ),
        ),
        migrations.AddField(
            model_name="examtemplate",
            name="pass_marks",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="pass_marks"
            ),
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="display_num_questions",
            field=models.PositiveIntegerField(
                default=1, verbose_name="display_num_questions"
            ),
        ),
    ]
