# Generated by Django 4.0.4 on 2022-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_question_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("scheduled", "Scheduled"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
