# Generated by Django 3.2.13 on 2022-06-02 10:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_exam_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="detail",
            field=ckeditor.fields.RichTextField(verbose_name="detail"),
        ),
    ]
