# Generated by Django 3.2.13 on 2022-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_exam_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("scheduled", "Scheduled"),
                    ("cancelled", "Cancelled"),
                    ("in_progress", "In Progress"),
                ],
                default="created",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
