# Generated by Django 3.2.13 on 2022-06-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_exam_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtemplate",
            name="duration",
            field=models.DurationField(
                help_text="Enter duration in HH:MM:SS format", verbose_name="duration"
            ),
        ),
    ]
