# Generated by Django 3.2.13 on 2022-06-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_examtemplate_duration"),
        ("exams", "0008_alter_option_detail"),
    ]

    operations = []
