# Generated by Django 3.2.13 on 2022-06-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_auto_20220608_1342"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examtemplate",
            name="pass_marks",
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="display_num_questions",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Display Question Number"
            ),
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="duration",
            field=models.DurationField(
                help_text="Enter duration in HH:MM:SS format", verbose_name="Duration"
            ),
        ),
        migrations.AlterField(
            model_name="examtemplate",
            name="full_marks",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Full Marks"
            ),
        ),
    ]
