# Generated by Django 3.2.13 on 2022-06-08 08:10
# Custom migration for calculating negative percentage against positive marks and negtive marks.

from django.db import migrations


def update_negpercentage_against_posmarks(apps, schema_editor):
    """Negative percentage are calculated against positive marks and negative marks."""

    Section = apps.get_model("exams", "Section")

    for section in Section.objects.all():
        section.neg_percentage = section.neg_marks / section.pos_marks
        section.save()


def reverse_update_negpercentage_against_posmarks(apps, schema_editor):
    """Negative marks are calculated against positive marks and negative percentage."""
    Section = apps.get_model("exams", "Section")

    for section in Section.objects.all():
        section.neg_marks = section.pos_marks * section.neg_percentage
        section.save()


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0013_auto_20220608_1354"),
    ]

    operations = [
        migrations.RunPython(
            update_negpercentage_against_posmarks,
            reverse_code=reverse_update_negpercentage_against_posmarks,
        ),
    ]
