# Generated by Django 3.2.13 on 2022-06-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0014_auto_20220608_1355"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="neg_marks",
        ),
    ]
