# Generated by Django 3.2.13 on 2022-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0015_remove_section_neg_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtemplate",
            name="description",
            field=models.TextField(
                default="No description available", verbose_name="description"
            ),
        ),
    ]
