# Generated by Django 3.2.13 on 2022-06-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0016_examtemplate_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="exams.examtemplate",
                verbose_name="Template",
            ),
        ),
    ]
