# Generated by Django 3.2.13 on 2022-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0017_alter_section_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtemplate",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("completed", "Completed")],
                default="draft",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
