# Generated by Django 3.2.13 on 2022-06-24 10:04

from django.db import migrations


def complete_previous_templates(apps, schema_editor):
    ExamTemplate = apps.get_model("exams", "ExamTemplate")
    for template in ExamTemplate.objects.all():
        template.status = "completed"
        template.save()


def complete_previous_templates_reverse(apps, schema_editor):
    ExamTemplate = apps.get_model("exams", "ExamTemplate")
    for template in ExamTemplate.objects.all():
        template.status = "draft"
        template.save()


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0018_examtemplate_status"),
    ]

    operations = [
        migrations.RunPython(
            complete_previous_templates,
            reverse_code=complete_previous_templates_reverse,
        ),
    ]
