# Generated by Django 3.2.13 on 2022-06-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0019_auto_20220624_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.section",
                verbose_name="section",
            ),
        ),
    ]
