# Generated by Django 3.2.13 on 2022-07-05 13:57

import django.db.models.deletion
from django.db import migrations, models

import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0021_alter_question_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.ImageField(
                        upload_to=exams.models.ExamImage.exam_image_path,
                        verbose_name="img",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="exams.exam",
                        verbose_name="exam",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "id"],
            },
        ),
    ]
