# Generated by Django 3.2.13 on 2022-09-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0023_alter_examtemplate_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="status",
        ),
    ]
