# Generated by Django 3.2.13 on 2022-10-20 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_auto_20221012_1655"),
        ("exams", "0024_remove_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_exam_related",
                related_query_name="exams_exams",
                to="courses.course",
                verbose_name="course",
            ),
        ),
    ]
