# Generated by Django 3.2.13 on 2022-11-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0025_exam_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("live", "Live"), ("practice", "Practice")],
                default="live",
                max_length=16,
                verbose_name="Exam Type",
            ),
        ),
    ]
