# Generated by Django 3.2.13 on 2022-11-10 11:51

from django.db import migrations


def publish_all_exams(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.all().update(is_published=True)


def reverse_publish_all_exams(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.all().update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0027_auto_20221110_1724"),
    ]

    operations = [
        migrations.RunPython(
            publish_all_exams,
            reverse_publish_all_exams,
        ),
    ]
