# Generated by Django 3.2.13 on 2022-06-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_instructor_id_remove_course_type_id"),
        ("notes", "0002_note_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="course_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="courses.course",
            ),
        ),
    ]
