# Generated by Django 3.2.13 on 2022-06-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_content_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="course_id",
            new_name="course",
        ),
    ]
