# Generated by Django 3.2.13 on 2022-06-30 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_auto_20220629_0953"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0006_alter_content_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="RecordedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(verbose_name="Entry Date")),
                ("link", models.URLField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_videos",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_recordedvideos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updater_recordedvideos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
