# Generated by Django 3.2.13 on 2022-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_auto_20220630_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("text", "Text")],
                default="pdf",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
