# Generated by Django 3.2.13 on 2022-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_auto_20220701_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_downloadable",
            field=models.BooleanField(default=True),
        ),
    ]
