# Generated by Django 4.0.4 on 2022-05-23 08:53

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "CourseCategory",
                "verbose_name_plural": "CourseCategorys.",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="password"
                    ),
                ),
                ("type_id", models.IntegerField(verbose_name="type_id")),
                ("instructor_id", models.IntegerField(verbose_name="instructor_id")),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=150, null=True, verbose_name="link"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Use'[algo]$[salt]$[hexdigest]' or use the                 < a href=\"password/\">change password form</a>.",
                        max_length=128,
                        null=True,
                        verbose_name="password",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("insession", "insession"),
                            ("upcoming", "upcoming"),
                            ("ended", "ended"),
                            ("cancelled", "cancelled"),
                        ],
                        default="upcoming",
                        max_length=64,
                        verbose_name="status",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=7,
                        verbose_name="price",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.coursecategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
    ]
