# Generated by Django 3.2.13 on 2022-06-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_course_instructor_id_remove_course_type_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-id"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
    ]
