# Generated by Django 3.2.13 on 2022-06-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursecategory",
            options={
                "ordering": ["id"],
                "verbose_name": "CourseCategory",
                "verbose_name_plural": "CourseCategories",
            },
        ),
    ]
