# Generated by Django 3.2.13 on 2022-06-29 04:08

from django.db import migrations, models

import courses.models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(default=0, verbose_name="Duration"),
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                default="default.png",
                upload_to=courses.models.Course.course_image_path,
                verbose_name="image",
            ),
        ),
    ]
