# Generated by Django 3.2.13 on 2022-07-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_coursecategory_options"),
        ("courses", "0004_auto_20220629_0953"),
    ]

    operations = []
