# Generated by Django 3.2.13 on 2022-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_merge_20220701_1042"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="duration",
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("insession", "insession"),
                    ("upcoming", "upcoming"),
                    ("ended", "ended"),
                ],
                default="upcoming",
                max_length=64,
                verbose_name="status",
            ),
        ),
    ]
