# Generated by Django 3.2.13 on 2022-08-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="description"
            ),
        ),
    ]
