# Generated by Django 3.2.13 on 2022-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
