# Generated by Django 3.2.13 on 2023-01-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_auto_20221116_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
