# Generated by Django 3.2.13 on 2022-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_auto_20221116_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.DurationField(
                help_text='The following data represents 20 days and 10 hours for the entered data "20 10:00:00".',
                verbose_name="Duration",
            ),
        ),
    ]
