# Generated by Django 3.2.13 on 2023-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.DurationField(
                help_text='The following data represents 20 days and 10 hours                 for the entered data "20 10:00:00".',
                verbose_name="Duration",
            ),
        ),
    ]
