# Generated by Django 3.2.13 on 2022-09-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseInfoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "CourseInfoCategory",
                "verbose_name_plural": "CourseInfoCategorys",
            },
        ),
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("introduction", models.TextField()),
                ("eligibility", models.TextField()),
                ("syllabus", models.TextField()),
                ("colleges", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courseinfos",
                        to="infocenter.courseinfocategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "CourseInfo",
                "verbose_name_plural": "CourseInfos",
            },
        ),
    ]
