# Generated by Django 3.2.13 on 2022-11-16 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counseling",
            options={
                "ordering": ["id"],
                "verbose_name": "Counseling",
                "verbose_name_plural": "Counselings",
            },
        ),
        migrations.AlterField(
            model_name="counseling",
            name="counsellor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counsellor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
