# Generated by Django 3.2.13 on 2022-11-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0002_auto_20221116_1613"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counseling",
            options={
                "ordering": ["-id"],
                "verbose_name": "Counseling",
                "verbose_name_plural": "Counselings",
            },
        ),
    ]
