# Generated by Django 3.2.13 on 2022-11-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0003_alter_counseling_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="counseling",
            old_name="date",
            new_name="created_at",
        ),
    ]
