# Generated by Django 3.2.13 on 2022-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0004_rename_date_counseling_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counseling",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="created_at"),
        ),
    ]
