# Generated by Django 3.2.13 on 2022-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counseling", "0005_alter_counseling_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counseling",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
