# Generated by Django 3.2.13 on 2023-04-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationmessage",
            options={"ordering": ["-created_at"]},
        ),
    ]
