# Generated by Django 3.2.13 on 2022-06-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="attendance",
            name="category",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                max_length=10,
                verbose_name="Category",
            ),
        ),
    ]
