# Generated by Django 3.2.13 on 2022-06-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_auto_20220607_1517"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="category",
        ),
    ]
