# Generated by Django 3.2.13 on 2022-06-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_remove_attendance_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacherattendancedetail",
            old_name="number_of_peroid",
            new_name="number_of_period",
        ),
    ]
