# Generated by Django 3.2.13 on 2022-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_auto_20221201_1702"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherattendancedetail",
            name="message",
            field=models.TextField(default="dummy", verbose_name="Message"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherattendancedetail",
            name="remarks",
            field=models.TextField(default="dummy", verbose_name="Remarks"),
            preserve_default=False,
        ),
    ]
