# Generated by Django 3.2.13 on 2022-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_teacherattendancedetail_number_of_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name="Attendance date"),
        ),
    ]
