# Generated by Django 3.2.13 on 2022-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(verbose_name="Attended date"),
        ),
    ]
