# Generated by Django 3.2.13 on 2023-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherattendancedetail",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="Remarks"),
        ),
    ]
